### ISSUE TITLE
k8s

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#16]
- [ ] Milestone 1
- [ ] Milestone 2
- [ ] Milestone 3

**Comment by gao-ti** [comment]
# Milestone 1

## Step 1 & 2

kubectl apply -f ./crd.yaml

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 # name must match the spec fields below, and be in the form: <plural>.<group>
 name: zhiyuangao-cr.example.com
spec:
 # group name to use for REST API: /apis/<group>/<version>
 group: example.com
 names:
   # plural name to be used in the URL: /apis/<group>/<version>/<plural>
   plural: zhiyuangao-cr
   # singular name to be used as an alias on the CLI and for display
   singular: zhiyuangao-cr
   # kind is normally the CamelCased singular type. Your resource manifests use this.
   kind: MyPlatform
   # shortNames allow shorter string to match your resource on the CLI
   shortNames:
   - myp
 scope: Namespaced
 versions:
   - name: v1beta1
     # Each version can be enabled/disabled by Served flag.
     served: true
     # One and only one version must be marked as the storage version.
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           spec:
             type: object
             properties:
               name:
                 type: string
               age:
                 type: string
               email:
                 type: string
               replicas:
                 type: integer
                 minimum: 1
             required: ["name", "age", "email"]
         required: ["spec"]
```
![image](https://user-images.githubusercontent.com/110180090/184928336-fcc93704-e3d4-408a-acd0-e2eb1f0172ac.png)

```
apiVersion: stable.example.com/v1
kind: zhiyuan-platform
metadata:
  name: object-zhiyuan-0
spec:
  name: "zhiyuan"
  age: "25"
  email: "zhiyuan.gao@trilogy.com"
```

## Step 3


![image](https://user-images.githubusercontent.com/110180090/184935401-aaf9d534-7224-4aff-8881-9344dae6e129.png)

![image](https://user-images.githubusercontent.com/110180090/184935445-f0e69e9e-1c33-4b99-834e-79830c4af624.png)

![image](https://user-images.githubusercontent.com/110180090/184938023-88951d14-d3ef-4969-a9bd-b695ac2e4ab0.png)

![image](https://user-images.githubusercontent.com/110180090/184939930-4785af48-2f7f-4d8b-9c94-cdffc76f43c7.png)

References
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
